Fix libtar build warnings since dev_t type changed
dev_t changed from uint16_t to unit32_t, so update here.

/home/haitao/code/stable/vela-miwear/apps/external/libtar/libtar/lib/libtar.h:288:28: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
  288 |  snprintf((oct), (octlen), "%*lo ", (octlen) - 2, (unsigned long)(num))
      |                            ^~~~~~~
lib/encode.c:152:2: note: in expansion of macro 'int_to_oct'
  152 |  int_to_oct(minor(device), t->th_buf.devminor, 8);
      |  ^~~~~~~~~~

Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>