Fix compiler error by commit ba285c15ea27c5e9
lib/handle.c:69:1: error: conflicting types for 'tar_open'
   69 | tar_open(TAR **t, char *pathname, tartype_t *type,
      | ^~~~~~~~
In file included from /home/xiaoxiang/vela/apps/external/libtar/lib/internal.h:16,
                 from lib/handle.c:13:
/home/xiaoxiang/vela/apps/external/libtar/lib/libtar.h:111:5: note: previous declaration of 'tar_open' was here
  111 | int tar_open(TAR **t, const char *pathname, tartype_t *type,
      |     ^~~~~~~~
lib/handle.c:95:1: error: conflicting types for 'tar_fdopen'
   95 | tar_fdopen(TAR **t, int fd, char *pathname, tartype_t *type,
      | ^~~~~~~~~~

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>